In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_excel('Online Retail Data Set.xlsx')

In [7]:
data.head(2)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [9]:
data.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [14]:
# data[data.StockCode == '85123A']

In [19]:
# data filtering
data[~data.Description.isnull()].shape

(540455, 8)

In [ ]:
condition_1 = data.Description.isnull()
condition_2 = data.StockCode == '85123A'
cond

data[condition_1 | condition_2]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
49,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:02:00,2.55,17850.0,United Kingdom
66,536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:32:00,2.55,17850.0,United Kingdom
220,536390,85123A,WHITE HANGING HEART T-LIGHT HOLDER,64,2010-12-01 10:19:00,2.55,17511.0,United Kingdom
262,536394,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2010-12-01 10:39:00,2.55,13408.0,United Kingdom
...,...,...,...,...,...,...,...,...
539342,581439,85123A,CREAM HANGING HEART T-LIGHT HOLDER,1,2011-12-08 16:30:00,5.79,NaN,United Kingdom
539979,581452,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2011-12-08 18:03:00,2.55,17675.0,United Kingdom
540217,581472,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-12-08 19:55:00,2.95,15796.0,United Kingdom
540837,581492,85123A,CREAM HANGING HEART T-LIGHT HOLDER,3,2011-12-09 10:03:00,5.79,NaN,United Kingdom
541639,581538,85123A,CREAM HANGING HEART T-LIGHT HOLDER,1,2011-12-09 11:34:00,2.95,14446.0,United Kingdom

In [20]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [23]:
data.Description.value_counts()

Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
                                      ...
LETTER "U" BLING KEY RING                1
wet                                      1
wet boxes                                1
????damages????                          1
lost                                     1
Name: count, Length: 4223, dtype: int64

In [24]:
data['total_price'] = data['Quantity'] * data['UnitPrice']
data.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [26]:
# 1. avg sales
data.groupby('Country')['total_price'].mean()

# 2. total sales
data.groupby('Country')['total_price'].sum()
# 3. max sales
data.groupby('Country')['total_price'].max()

Country
Australia                 1718.40
Austria                    360.00
Bahrain                    205.74
Belgium                    165.00
Brazil                     175.20
Canada                     550.94
Channel Islands            408.00
Cyprus                     320.69
Czech Republic              70.80
Denmark                    428.40
EIRE                      2365.20
European Community          60.00
Finland                    551.20
France                    4161.06
Germany                    876.00
Greece                     175.20
Hong Kong                 2653.95
Iceland                    249.60
Israel                     350.40
Italy                      300.00
Japan                     3794.40
Lebanon                    153.00
Lithuania                  122.40
Malta                      455.00
Netherlands               4992.00
Norway                     700.00
Poland                     120.00
Portugal                  1241.98
RSA                         38.25
Saudi Arabia                19.80
Singapore                 3949.32
Spain                     1350.00
Sweden                    1188.00
Switzerland                360.00
USA                         81.36
United Arab Emirates       153.00
United Kingdom          168469.60
Unspecified                 69.36
Name: total_price, dtype: float64

In [28]:
result_df =data.groupby('Country').agg({
    'total_price': ['mean', 'sum', 'max'],
    'Description': ['count']
})
result_df.head()

          total_price                     Description
                 mean        sum      max       count
Country
Australia  108.877895  137077.27  1718.40        1259
Austria     25.322494   10154.32   360.00         401
Bahrain     28.863158     548.40   205.74          19
Belgium     19.773301   40910.96   165.00        2069
Brazil      35.737500    1143.60   175.20          32

In [29]:
data.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [30]:
data.rename(columns={'Description': 'Product_Description'}, inplace=True)

In [34]:
def data_checks(df):
    checks ={
        'size_of_data': df.shape[0],
        'num_of_columns': df.shape[1],
        'missing_values': df.isnull().sum().sum(),
        'pct_missing': round(df.isnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100,2)
    }
    return checks

data_checks(data)

{'size_of_data': 541909,
 'num_of_columns': 9,
 'missing_values': np.int64(136534),
 'pct_missing': np.float64(2.8)}

In [36]:
data.groupby(['Country', 'Product_Description']).agg({
    'total_price': ['mean', 'sum', 'max'],
    'Product_Description': ['count']
})

                                          total_price                \
                                                 mean    sum    max
Country     Product_Description
Australia    DOLLY GIRL BEAKER                  216.0  216.0  216.0
             I LOVE LONDON MINI BACKPACK         16.6   16.6   16.6
            10 COLOUR SPACEBOY PEN               40.8   40.8   40.8
            12 PENCIL SMALL TUBE WOODLAND       211.2  211.2  211.2
            12 PENCILS TALL TUBE POSY            39.9   79.8   69.6
...                                               ...    ...    ...
Unspecified WRAP POPPIES  DESIGN                 10.5   10.5   10.5
            WRAP SUKI AND FRIENDS                10.5   10.5   10.5
            WRAP VINTAGE PETALS  DESIGN          10.5   10.5   10.5
            WRAP WEDDING DAY                     10.5   10.5   10.5
            ZINC METAL HEART DECORATION           2.5    2.5    2.5

                                          Product_Description
                                                        count
Country     Product_Description
Australia    DOLLY GIRL BEAKER                              1
             I LOVE LONDON MINI BACKPACK                    1
            10 COLOUR SPACEBOY PEN                          1
            12 PENCIL SMALL TUBE WOODLAND                   1
            12 PENCILS TALL TUBE POSY                       2
...                                                       ...
Unspecified WRAP POPPIES  DESIGN                            1
            WRAP SUKI AND FRIENDS                           1
            WRAP VINTAGE PETALS  DESIGN                     1
            WRAP WEDDING DAY                                1
            ZINC METAL HEART DECORATION                     1

[20176 rows x 4 columns]

In [38]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Product_Description', 'Quantity',
       'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'total_price'],
      dtype='str')

In [40]:
data[['StockCode', 'Product_Description', 'Quantity']]

       StockCode                  Product_Description  Quantity
0         85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1          71053                  WHITE METAL LANTERN         6
2         84406B       CREAM CUPID HEARTS COAT HANGER         8
3         84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...                                  ...       ...
541904     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905     22899         CHILDREN'S APRON DOLLY GIRL          6
541906     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908     22138        BAKING SET 9 PIECE RETROSPOT          3

[541909 rows x 3 columns]

In [42]:
def tagg_to_total_sales(sales):
    if sales > 100:
        return "High"
    elif sales > 50:
        return "Medium"
    else:
        return "Low"
    

data['sales_tag'] = data['total_price'].apply(tagg_to_total_sales)

In [ ]:
data.sales_tag.value_counts()

sales_tag
Low       510819
Medium     17536
High       13554
Name: count, dtype: int64

In [54]:
data.head(5)

,InvoiceNo,StockCode,Product_Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_price,sales_tag
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,Low
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Low
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,Low
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Low
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Low

In [55]:
# loc vs iloc?
# .loc is label-based( means col labels), while .iloc is position-based
data.loc[data['Country'] == 'United Kingdom', 'Product_Description']

# vs#

data.iloc[0:10, 2]

0     WHITE HANGING HEART T-LIGHT HOLDER
1                    WHITE METAL LANTERN
2         CREAM CUPID HEARTS COAT HANGER
3    KNITTED UNION FLAG HOT WATER BOTTLE
4         RED WOOLLY HOTTIE WHITE HEART.
5           SET 7 BABUSHKA NESTING BOXES
6      GLASS STAR FROSTED T-LIGHT HOLDER
7                 HAND WARMER UNION JACK
8              HAND WARMER RED POLKA DOT
9          ASSORTED COLOUR BIRD ORNAMENT
Name: Product_Description, dtype: object

In [ ]:
#https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
#https://www.kaggle.com/datasets/lakshmi25npathi/online-retail-dataset/data